-- Create events table
create table public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  date date not null,
  time text not null,
  location text not null,
  capacity integer not null,
  price numeric not null,
  category text not null,
  image text not null,
  description text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert sample data
insert into public.events (title, date, time, location, capacity, price, category, image, description)
values
  ('Annual Tech Symposium 2026', '2026-03-15', '09:00 AM', 'Grand Auditorium', 500, 25, 'Technology', 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=1000', 'Join us for a day of innovation and technology talks from industry leaders.'),
  ('Campus Music Festival', '2026-04-20', '06:00 PM', 'University Lawn', 2000, 15, 'Entertainment', 'https://images.unsplash.com/photo-1459749411177-8c4750bb0e5f?auto=format&fit=crop&q=80&w=1000', 'An evening of live music, food, and fun under the stars.'),
  ('Future Leaders Workshop', '2026-03-25', '10:00 AM', 'Business School Hall B', 50, 40, 'Workshop', 'https://images.unsplash.com/photo-1544531586-fde5298cdd40?auto=format&fit=crop&q=80&w=1000', 'Intensive leadership training for aspiring student leaders.'),
  ('Art & Design Exhibition', '2026-05-10', '11:00 AM', 'Creative Arts Center', 300, 10, 'Arts', 'https://images.unsplash.com/photo-1460661631910-d63f06b473a2?auto=format&fit=crop&q=80&w=1000', 'Showcasing the best art and design projects from students.');

-- Create registrations table
create table public.registrations (
  id uuid default gen_random_uuid() primary key,
  event_id bigint references public.events(id),
  full_name text not null,
  email text not null,
  student_id text not null,
  department text,
  year text,
  payment_id text,
  amount numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.events enable row level security;
alter table public.registrations enable row level security;

-- Policies
create policy "Enable read access for all users" on public.events for select using (true);
create policy "Enable insert for all users" on public.registrations for insert with check (true);
create policy "Enable select for own registrations" on public.registrations for select using (true);
